name: Bug Report
description: Report a bug or unexpected behavior in typed_argparser
labels: [bug, pending]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to typed_argparser!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.
        Please provide as much detail as possible to make understanding and solving your problem as quick as possible.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        from typed_argparser import argparser

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, typed_argparser & OS Version
      description: |
        Which version of Python & typed_argparser are you using, and which Operating System?
        Please run the following command for the version and copy the output below:

        ```bash
        python -c "import typed_argparser; print(typed_argparser.__version__)"
        ```

      render: Text
    validations:
      required: true
