blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: "https://github.com/ajatkj/typed_argparser/discussions/new?category=q-a"
    about: Ask a question about how to use typed_argparser using github discussions
